apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    app.kubernetes.io/name: kubecell
    app.kubernetes.io/managed-by: kubecell
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: https
      port: 443
      targetPort: 9443
