apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/kubecell.io_cells.yaml
- bases/kubecell.io_virtualclusters.yaml
- bases/kubecell.io_virtualclusterplans.yaml
- bases/kubecell.io_virtualnodeclasses.yaml
